import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.css';
<<<<<<< HEAD
import 'bootstrap/dist/css/bootstrap.min.css';
=======

>>>>>>> 707ab7863bf426f46906266df4d176d73cd48e11
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
